### PR TITLE
Add support for dark mode in popup

### LINKED ISSUE #569: [Suggestion] (Optional) dark theme support for free form translation popup
**Is your feature request related to a problem? Please describe.**
The free form translation popup is understandably huge but the whitespace blinds my eyes.

**Describe the solution you'd like**
Add (optional) dark theme support for the popup. Maybe shrink top and bottom whitespaces a little bit.

**Describe alternatives you've considered**
None...

**Additional context**
Screenshot of a fullscreen 1920×1080 125% Scaled popup
Firefox Translation popup

### PR DESCRIPTION
**Pull request by veyndan**
Closes #569.

Screenshot 2023-01-25 at 23 14 33

### CODE REVIEW

**Comment by andrenatal** [comment]
The label next to the detected language is unreadable on dark mode . Also, could you test this on Android as well @veyndan ?
Screenshot 2023-01-26 at 2 51 04 PM

**Comment by andrenatal** [comment]
No worries here @veyndan , I've landed the fixes.

**Comment by andrenatal** [comment]
And also tested on Android. Thanks again!

**Comment by veyndan** [comment]
Thanks for the fixup (for future prosperity, it's https://github.com/mozilla/firefox-translations/commit/eef740b332e4e6c9ad6b4cd3bb12e736206fa7aa)!

**Pull request merged**
