### PR TITLE
Add Ukrainian models

### LINKED ISSUE #166: Dump of Ukranian-centric models
A dump of models from Helsinki: https://github.com/Helsinki-NLP/UkrainianLT/blob/main/translateLocally-models.json

"Additional ones are on the way. The quality might be a bit questionable but it is hard for me to judge."

These have some languages where we don't have en support yet, need to revise the pivoting assumptions.

### PR DESCRIPTION
**Pull request by eu9ene**
The models were not quantized using browsermt marian (it produces so-called alpha models) and should be used with `gemm-precision: int8shiftAll`. See [browsermt/marian-dev](https://github.com/browsermt/marian-dev/blob/199201eb89b2941afdadb14164e936d412f897ad/src/common/config_parser.cpp#L927) config docs for an explanation of the difference. This mode is ~15% slower https://github.com/mozilla/translation-service/pull/20#issuecomment-1152880275. 

Also, we need to update Gecko to support non-alpha models, so they are slow for now ( I assume the same as usage on ARM).

We distinguish between different model types based on naming convention in the model registy.

The models include two different vocabularies for source and target language, unlike all the other models that currently reuse one vocabulary. I added two registry keys to support this.

Also, the model itself is a bit heavier and there's more data to download because of two vocabularies.

Despite all that it's good to have an extra language. It's marked as "Beta", so there shouldn't be expectations for speed or quality.

fixes #166

### CODE REVIEW

**Comment by andrenatal** [comment]
There's so many caveats that I don't know if we should implement it now.

**Comment by andrenatal** [comment]
I will test it tomorrow morning.

**Comment by eu9ene** [comment]
It looks pretty usable to me on a regular website like this one https://www.pravda.com.ua/

Of course, if you will try to translate huge texts on Wikipedia it will be noticeably slow but it's the same for our other models.

**Comment by andrenatal** [comment]
I've pulled and tested the xpi built from CI and Ukrainian is not being displayed in the translation bar at least in a pt-br browser.

**Review by andrenatal — CHANGES_REQUESTED** [review]
Translation bar does not display Ukrainian in a pt-br browser

**Comment by andrenatal** [comment]
Same on english browser
Screen Shot 2022-06-23 at 4 20 04 PM

**Comment by eu9ene** [comment]
> Translation bar does not display Ukrainian in a pt-br browser

did other languages work? I can see it working using `npm run once` but when I do `npm build` and then install it manually the translation bar does not appear at all

**Comment by andrenatal** [comment]
> > Translation bar does not display Ukrainian in a pt-br browser
> 
> did other languages work? I can see it working using `npm run once` but when I do `npm build` and then install it manually the translation bar does not appear at all

yes
Screen Shot 2022-06-23 at 4 33 12 PM

**Comment by eu9ene** [comment]
not sure what the issue was but I synced it with main and it looks working now

**Review by andrenatal — APPROVED** [review]

**Pull request merged**
