### PR TITLE
Incoporate localization for form translations

### LINKED ISSUE #142: Localization for Form Translations

### PR DESCRIPTION
**Pull request by andrenatal**
Fixes #142 . 

Depends on https://github.com/mozilla-l10n/firefox-translations-l10n/pull/1

### CODE REVIEW

**Comment by andrenatal** [comment]
@abhi-agg what was blocking this is now merged, we need to merge this too

**Comment by flodolo** [comment]
Does this need code changes to use the language name instead of the locale code (like in the screencast)?

**Comment by andrenatal** [comment]
@flodolo Yes, I've just pushed an update

**Comment by andrenatal** [comment]
@abhi-agg can you review this?

**Comment by andrenatal** [comment]
or @eu9ene

**Review by eu9ene — COMMENTED** [review]
lgtm, but there are conflicts with the main branch

**Comment by andrenatal** [comment]
> lgtm, but there are conflicts with the main branch

fixed

**Review by eu9ene — APPROVED** [review]

**Pull request merged**
