### PR TITLE
Replaces low-res png icons by a single svg

### LINKED ISSUE #389: Replace the AMO (and extension's) icons by one in high resolution
**Describe the bug**
The icon used in the AMO listing is in low-res

**To Reproduce**
1. Go to https://addons.mozilla.org/en-US/firefox/addon/firefox-translations/ and notice it

**Expected behavior**
A high resolution icon

**Screenshots**
Screen Shot 2022-06-07 at 7 35 56 PM

### PR DESCRIPTION
**Pull request by andrenatal**
fixes #389 

@Rob--W is this the right approach to use svg icons in the manifest? 

It is cool that the browser_action one now follows the browser's theme, although is not possible to read the letters. 
Screen Shot 2022-06-10 at 10 19 00 AM

### CODE REVIEW

**Comment by lonnen** [comment]
Do we need a 1-color version for the URL bar? Now that I look at it in context page actions all seem one color. It's an easy enough change if we need it.

**Comment by lonnen** [comment]
```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg width="264px" height="292px" viewBox="0 0 264 292" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <defs></defs>
    <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g fill="#000000" fill-rule="nonzero">
            <path d="M47.1009025,179.531325 L33.7877403,195.15982 C29.0323196,200.74227 20.6586441,193.609139 25.4140648,188.026689 L48.3899823,161.05496 C48.4107785,161.030236 48.4317883,161.005698 48.4530091,160.981349 C50.7278205,158.354828 53.8134632,158.605367 55.8991832,160.190473 C56.0509439,160.304381 56.1978897,160.427032 56.3392872,160.558367 C56.6030277,160.800472 56.8456287,161.065394 57.0624698,161.349198 L79.7877403,188.026689 C81.7575,190.339016 81.4797947,193.810333 79.167468,195.780092 C76.8551414,197.749852 73.3838245,197.472147 71.4140648,195.15982 L58.1009025,179.531325 L58.1009025,238.093255 L118.600903,238.093255 C121.638469,238.093255 124.100903,240.555688 124.100903,243.593255 C124.100903,246.630821 121.638469,249.093255 118.600903,249.093255 L52.6009025,249.093255 C49.5633364,249.093255 47.1009025,246.630821 47.1009025,243.593255 L47.1009025,179.531325 Z M47.1009025,179.531325 L47.1009025,164.630392 L58.1009025,165.577109 Z M212.5,40 C215.537566,40 218,42.4624339 218,45.5 L218,109.561929 L231.313162,93.9334345 C236.068583,88.3509841 244.442258,95.4841151 239.686838,101.066566 L216.71092,128.038295 C216.690124,128.063019 216.669114,128.087556 216.647893,128.111906 C214.373082,130.738427 211.287439,130.487887 209.201719,128.902781 C209.049959,128.788873 208.903013,128.666223 208.761615,128.534888 C208.497875,128.292783 208.255274,128.027861 208.038433,127.744057 L185.313162,101.066566 C183.343402,98.7542389 183.621108,95.282922 185.933434,93.3131622 C188.245761,91.3434025 191.717078,91.6211078 193.686838,93.9334345 L207,109.561929 L207,51 L146.5,51 C143.462434,51 141,48.5375661 141,45.5 C141,42.4624339 143.462434,40 146.5,40 L212.5,40 Z M207,123.516146 L207,109.561929 L218,109.561929 Z M145,144 L247,144 C253.627417,144 259,149.372583 259,156 L259,270 C259,276.627417 253.627417,282 247,282 L145,282 C138.372583,282 133,276.627417 133,270 L133,156 C133,149.372583 138.372583,144 145,144 Z M223.717881,251 C227.676898,251 230.76988,250.338786 233,249.029013 L233,239.006405 C231.480473,239.512597 230.160801,239.765693 229.040983,239.765693 C227.010717,239.765693 225.817936,239.057024 225.46264,237.639685 C225.107343,236.22551 224.929695,233.9951 224.929695,230.957946 L224.929695,190.563795 C224.929695,186.0049 224.070005,182.312859 222.344279,179.478182 C220.615381,176.640341 218.334505,174.441568 215.492134,172.869208 C212.649762,171.303175 209.477472,170.265481 205.975265,169.759289 C202.473057,169.25626 198.945471,169 195.392507,169 C191.027436,169 186.865392,169.458737 182.906375,170.366719 C178.947357,171.277866 175.445149,172.774297 172.399751,174.846522 C169.354353,176.921911 166.918035,179.63004 165.090796,182.970909 C163.263557,186.311779 162.248425,190.415101 162.045398,195.271384 L174.98834,195.271384 C175.292879,189.500791 177.272388,185.5778 180.926866,183.502411 C184.581344,181.430186 189.149441,180.389328 194.631157,180.389328 C196.661422,180.389328 198.717066,180.54435 200.798088,180.848065 C202.875938,181.151781 204.757106,181.759211 206.432074,182.670358 C208.107043,183.581504 209.477472,184.900768 210.543362,186.618658 C211.609251,188.342876 212.142196,190.617578 212.142196,193.452255 C212.142196,195.881978 211.431603,197.732744 210.010417,198.995062 C208.586059,200.257379 206.660479,201.222308 204.224161,201.877194 C201.787842,202.538408 198.970849,203.041437 195.773181,203.395771 C192.575513,203.750106 189.200197,204.284772 185.647233,204.990277 C182.297295,205.600872 179.023492,206.356997 175.825824,207.268143 C172.628156,208.179289 169.785785,209.517535 167.29871,211.292372 C164.808462,213.064046 162.806748,215.367221 161.284049,218.201898 C159.76135,221.036575 159,224.681161 159,229.135653 C159,233.083954 159.685215,236.450133 161.055644,239.234191 C162.426073,242.021413 164.304068,244.296115 166.68963,246.067788 C169.07202,247.836298 171.841428,249.104942 174.98834,249.864231 C178.132079,250.620356 181.482017,251 185.038153,251 C190.51987,251 195.620911,250.063544 200.341278,248.190632 C205.061645,246.317721 209.195139,243.255257 212.751275,239.003241 C212.751275,243.252093 213.744202,246.317721 215.723711,248.190632 C217.703219,250.063544 220.367943,251 223.717881,251 Z M205.597762,211.441066 C208.233935,210.884255 210.368886,209.998418 211.993098,208.783556 L211.993098,221.992014 C211.993098,223.81747 211.536288,225.769474 210.622669,227.838535 C209.70905,229.913924 208.287864,231.837455 206.359112,233.609128 C204.43036,235.383965 201.943285,236.855087 198.897887,238.016166 C195.852489,239.180408 192.198011,239.762529 187.934454,239.762529 C186.005702,239.762529 184.102328,239.560052 182.224332,239.155099 C180.343165,238.753308 178.722125,238.092095 177.351695,237.180948 C175.981266,236.269802 174.861448,235.08025 174.001758,233.612292 C173.138895,232.144334 172.707463,230.347351 172.707463,228.221343 C172.707463,224.981712 173.443435,222.428604 174.915377,220.552529 C176.387319,218.679617 178.290693,217.236969 180.625498,216.224584 C182.960304,215.215363 185.596476,214.481384 188.543533,214.025811 C191.487418,213.567074 194.405924,213.16212 197.299053,212.807786 C200.192181,212.453451 202.955245,211.997878 205.597762,211.441066 Z M19,6 L121,6 C127.627417,6 133,11.372583 133,18 L133,132 C133,138.627417 127.627417,144 121,144 L19,144 C12.372583,144 7,138.627417 7,132 L7,18 C7,11.372583 12.372583,6 19,6 Z M79.8114264,131.89967 C80.1886639,132.161919 80.5705706,132.376051 80.6601081,132.375518 C80.7496424,132.374982 82.6282748,131.901174 84.834847,131.32261 C97.2176057,128.075842 105.920435,123.909523 111.813868,118.406905 C118.348914,112.305217 121.414176,105.179523 121.399952,96.1225 C121.385552,86.9536709 118.069568,80.53459 110.825163,75.6518347 C106.073833,72.4494188 99.8984428,70.5956913 91.8162903,69.9457502 L89.2307802,69.7378327 L87.7434549,65.9459886 C86.2314591,62.0912547 85.3255424,60.7019385 84.3240148,60.7019385 C83.6569726,60.7019385 83.5418482,61.1734376 83.3143552,64.8370087 C83.2202071,66.3532012 82.9967909,68.1095309 82.8178765,68.7399668 C82.4662538,69.9789594 82.5080892,69.9589028 79.1255343,70.5103282 C73.6258737,71.4068849 67.636891,72.9304898 62.4957506,74.7409614 L59.9077901,75.6523217 L60.1149672,71.6230235 C60.597796,62.2326496 62.0182885,50.9792856 62.7481701,50.7623507 C63.0143012,50.6832544 64.9679818,50.3299847 67.0896858,49.9773091 C72.4514928,49.0860514 82.3760096,47.0860772 86.069293,46.1525652 C94.043092,44.1371074 95.641391,43.3470854 95.4283904,41.5264477 C95.2036534,39.6054594 90.8636282,37.4623934 86.686516,37.2097866 C84.4417655,37.0740399 84.0915439,37.1326813 82.8288723,37.8557121 C80.0425024,39.4512458 78.8414266,39.8515666 71.7998812,41.5316732 C67.855638,42.4727662 64.4383766,43.242753 64.2059644,43.242753 C63.8799596,43.242753 64.1921695,41.2303675 65.5721906,34.4365849 C66.5560317,29.5931924 67.5761933,24.9412384 67.8392198,24.0989092 C68.1022463,23.2565801 68.3159042,22.2228126 68.3140124,21.801648 C68.3052849,19.856903 65.7225801,16.3630505 62.8360472,14.3911151 C61.8453642,13.7143266 57.6810964,12 57.0278029,12 C56.7608077,12 55.9796718,13.0349193 55.9796718,13.3886577 C55.9796718,13.6229538 56.7459233,14.6669763 57.6824512,15.7087078 C58.6189791,16.7504392 59.4723763,17.9473888 59.5788905,18.3685963 C59.8573908,19.4699217 59.4890598,25.957265 58.9144191,30.0717885 C58.0447056,36.2990971 56.5449493,44.3042776 56.1798712,44.6678514 C55.5791558,45.2660949 45.1388967,46.4110377 40.0861796,46.4327882 C35.0737579,46.454364 34.0530994,46.2047436 31.2226197,44.2650465 C29.0505873,42.7765774 27.2863541,44.1712417 28.3978493,46.4980855 C29.1277155,48.0260185 33.1992578,52.2595279 34.8778915,53.2359099 C36.0822818,53.9364459 36.3151415,53.968727 38.1306659,53.6868041 C39.2061986,53.5197901 41.4054938,53.3057405 43.0179888,53.2111393 C44.6304839,53.116535 48.0053914,52.7488047 50.5177822,52.3939575 C53.030173,52.0391103 55.1639345,51.8263686 55.2594806,51.9211965 C55.3550236,52.0160243 55.2111829,53.7203563 54.9398362,55.7085961 C54.1904565,61.1995008 53.5294909,68.5696785 53.3078215,73.9065257 L53.1085325,78.7045825 L51.9980588,79.2202839 C47.7758122,81.1810852 40.1199695,85.9598022 35.6124269,89.4480678 C32.3496751,91.9730244 26.0895587,97.9669465 24.3675034,100.214832 C20.459482,105.316167 18.752166,110.699529 19.0288701,117.048133 C19.2984176,123.232511 21.0343696,126.372171 24.8370342,127.552841 C27.1615269,128.274561 28.8069262,128.227501 32.3387317,127.338292 C38.626762,125.755142 45.3484686,122.644543 52.3607237,118.072736 C55.9768573,115.715109 56.9055063,115.329111 56.9055063,116.183671 C56.9055063,116.35489 57.4675218,117.921668 58.1544262,119.665397 C59.1406992,122.169078 59.6661473,123.071466 60.6529943,123.956347 C61.6539633,124.853896 62.0656233,125.03931 62.721648,124.888092 C63.8493144,124.628155 65.0929386,123.109478 65.5778752,121.400148 C66.285364,118.90636 66.0686755,117.226496 64.5125915,113.141653 C63.7234226,111.070019 63.0777363,109.262191 63.0777363,109.124257 C63.0777363,108.986327 64.0616762,107.786752 65.2642673,106.458537 C71.2110381,99.8905628 79.0216063,89.462954 85.6095823,79.2962345 L88.538185,74.7767497 L91.1613828,74.9655631 C100.74601,75.6554552 107.25064,79.3133506 110.177952,85.6595807 C111.549098,88.6321418 111.879794,90.3407222 112.057471,95.3703828 C112.286108,101.842586 111.740409,104.955503 109.656609,109.066014 C107.911355,112.508714 106.265663,114.459374 102.436982,117.623521 C96.9327419,122.17241 90.2734828,125.894154 83.4560295,128.231648 C81.6792605,128.840848 79.9780396,129.561591 79.6755386,129.833305 C78.9297543,130.503177 78.983752,131.324283 79.8114264,131.89967 Z M40.7725287,111.939048 C39.214343,112.39743 37.7400953,112.632444 35.9222113,112.712251 C31.6961595,112.897779 31.0211496,112.251266 31.2630511,108.249782 C31.5928329,102.794598 34.6868031,98.2602149 41.9463229,92.5928529 C44.1647063,90.8610085 49.6041184,87.2264045 51.8640778,85.9658343 L53.2549896,85.1900024 L53.4176618,89.6065945 C53.5983374,94.5120588 53.9312084,98.5532985 54.4461928,102.09354 C54.7589611,104.243668 54.7526408,104.469027 54.3717018,104.749666 C51.0590246,107.190129 43.7115971,111.074445 40.7725287,111.939048 Z M64.1131777,97.9273409 C62.9586642,99.2993321 61.8867638,100.464304 61.7311739,100.516167 C61.5561209,100.574518 61.3855578,100.051025 61.2837275,99.1428599 C61.0331549,96.9081583 60.6302831,89.1053533 60.6248349,86.3814703 L60.6199951,83.9610043 L63.0918503,82.9230483 C66.7135643,81.4022565 69.7851245,80.4266343 73.2634836,79.692222 C77.8014877,78.7340777 77.6344942,78.5902867 75.6726043,81.7666536 C71.8516436,87.9529262 68.1401264,93.1418192 64.1131777,97.9273409 Z"></path>
        </g>
    </g>
</svg>
```

1-color-with-transparency

**Comment by lonnen** [comment]
changing the `fill=` field on the inner `g` element from `#000000` to whatever color you need. I run darkmode so all my icons are white... not sure if that's different in the default scheme or not

**Review by Rob--W — APPROVED** [review]
Syntax in manifest.json looks good.

The preview of the png looks different from the SVG itself (at least on Github). Is the difference intended? Why is there even a PNG if only the SVG version is used?

**Comment by andrenatal** [comment]
I left the PNG there since that's what we use on AMO, just to historical purposes. We can use the dark and white version for the page actions only, but are we sure they are all dark and white regardless of the theme in use? @lonnen @Rob--W

**Comment by lonnen** [comment]
Dark and Light modes present differently. See also:

* https://bugzilla.mozilla.org/show_bug.cgi?id=1421329
* https://bugzilla.mozilla.org/show_bug.cgi?id=1377302
* https://stackoverflow.com/questions/48540523/firefox-pick-page-action-icon-for-dark-light-themes

I'm not sure what the "right" implementation is here. Maybe something hacky with the css media feature: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

**Pull request merged**
